# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('new-other', 'new-other'), ('used', 'used'), ('vintage', 'vintage'), ('antique', 'antique')], default='new', max_length=20),
        ),
    ]
