# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160226_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='sku',
            field=models.IntegerField(unique=True),
        ),
    ]
