# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20160227_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thingcategory',
            options={'verbose_name_plural': 'thing categories'},
        ),
    ]
