# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160227_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
