# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160227_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='category',
            new_name='categories',
        ),
    ]
