# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160227_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='categories',
        ),
        migrations.DeleteModel(
            name='ThingCategory',
        ),
    ]
