# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_thingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='categories',
            field=models.ManyToManyField(to='catalog.ThingCategory'),
        ),
        migrations.AlterField(
            model_name='thingcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.ThingCategory'),
        ),
    ]
