# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20160228_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thingattribute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='thingattributevalue',
            options={'ordering': ['thing_attribute__name']},
        ),
        migrations.AlterField(
            model_name='thingattribute',
            name='thing_categories',
            field=models.ManyToManyField(related_name='thing_attributes', to='catalog.ThingCategory'),
        ),
        migrations.AlterField(
            model_name='thingattributevalue',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.Thing'),
        ),
        migrations.AlterField(
            model_name='thingattributevalue',
            name='thing_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.ThingAttribute'),
        ),
        migrations.AlterField(
            model_name='thingattributevalue',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
