# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20160302_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='entered',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='featured_in_categories',
            field=models.ManyToManyField(related_name='featured_things', to='catalog.ThingCategory'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='categories',
            field=models.ManyToManyField(related_name='things', to='catalog.ThingCategory'),
        ),
    ]
