# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20160303_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='featured_in_categories',
            field=models.ManyToManyField(blank=True, related_name='featured_things', to='catalog.ThingCategory'),
        ),
        migrations.AlterField(
            model_name='thingattribute',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
